###########################
# Basement Sensor
###########################
- platform: template
  sensors:  
    basement_multisensor_motion:
      friendly_name: 'Basement Motion'
      device_class: motion
      value_template: "{{ (not is_state('sensor.basement_sensor_burglar','0')) }}"
    basement_multisensor_tamper:
      friendly_name: 'Basement Sensor Tampering'
      device_class: vibration
      value_template: "{{ is_state('sensor.basement_sensor_burglar', '3') }}"
