###########################
# Entryway Sensor
###########################
- platform: template
  sensors:  
    entryway_multisensor_motion:
      friendly_name: 'Entryway Motion'
      device_class: motion
      value_template: "{{ (not is_state('sensor.entryway_sensor_burglar','0')) }}"
    entryway_multisensor_tamper:
      friendly_name: 'Entryway Sensor Tampering'
      device_class: vibration
      value_template: "{{ is_state('sensor.entryway_sensor_burglar', '3') }}"
