###########################
# Garage Sensor
###########################
- platform: template
  sensors:  
    garage_multisensor_motion:
      friendly_name: 'Garage Motion'
      device_class: motion
      value_template: "{{ (not is_state('sensor.garage_sensor_burglar','0')) }}"
    garage_multisensor_tamper:
      friendly_name: 'Garage Sensor Tampering'
      device_class: vibration
      value_template: "{{ is_state('sensor.garage_sensor_burglar', '3') }}"

