###########################
# Guest Room Sensor
###########################
- platform: template
  sensors:  
    guest_room_multisensor_motion:
      friendly_name: 'Guest Room Motion'
      device_class: motion
      value_template: "{{ (not is_state('sensor.guest_room_sensor_burglar','0')) }}"
    guest_room_multisensor_tamper:
      friendly_name: 'Guest Room Sensor Tampering'
      device_class: vibration
      value_template: "{{ is_state('sensor.guest_room_sensor_burglar', '3') }}"
