###########################
# Mainfloor Sensor
###########################
- platform: template
  sensors:  
    mainfloor_multisensor_motion:
      friendly_name: 'Main Floor Motion'
      device_class: motion
      value_template: "{{ (not is_state('sensor.main_floor_sensor_burglar','0')) }}"
    mainfloor_multisensor_tamper:
      friendly_name: 'Main Floor Sensor Tampering'
      device_class: vibration
      value_template: "{{ is_state('sensor.main_floor_sensor_burglar', '3') }}"
