###########################
# Office Sensor
###########################
- platform: template
  sensors:  
    office_multisensor_motion:
      friendly_name: 'Office Motion'
      device_class: motion
      value_template: "{{ (not is_state('sensor.office_sensor_burglar','0')) }}"
    office_multisensor_tamper:
      friendly_name: 'Office Sensor Tampering'
      device_class: vibration
      value_template: "{{ is_state('sensor.office_sensor_burglar', '3') }}"
