homeassistant:
  name: !secret haname
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include configs/customize.yaml 
  auth_providers: !include configs/auth.yaml

# Enables the frontend
frontend: !include configs/frontend.yaml

# Enables configuration UI
config:

#Load HTTP Config
http: !include configs/http.yaml

#Load Notify Config
notify: !include configs/notify.yaml

#Load Alert Config
alert: !include configs/alert.yaml

#Load MQTT Config
mqtt: !include configs/mqtt.yaml

#Load MQTT Lights
light: !include configs/mqtt_light.yaml

#Load Cover
cover:
  platform: zwave

#Load Zwave
zwave: !include configs/zwave.yaml

#LOAD Manually created automations
automation old: !include_dir_merge_list configs/automations

#LOAD Automations from editor
automation: !include automations.yaml

#Load Google Assistant
google_assistant: !include configs/gassistant.yaml

#Load Device Tracker
device_tracker: !include configs/device_tracker.yaml

# Checks for available updates
updater:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook: !include configs/logbook.yaml

# Track the sun
sun:

# Text to speech
tts:
  - platform: google
    cache: true
    cache_dir: /config/tts
    time_memory: 300
#Load Logging Config
logger: !include configs/logging.yaml

#Load Media Config
media_player: !include configs/media.yaml

#Load Sensor Config
sensor: !include_dir_merge_list configs/sensors

#Load Binary Sensor Config
binary_sensor: !include_dir_merge_list configs/binary_sensors

#Load Scenes Config
scene: !include_dir_merge_list configs/scenes

#Load HA Groups
group: !include_dir_merge_named configs/groups

#Load Scripts
script: !include_dir_merge_named configs/scripts

#LOAD SLIDERS
input_number: !include configs/input_slider.yaml

#LOAD INPUT BOOLEANS
input_boolean: !include configs/input_boolean.yaml

#Point HA to MariaDB
recorder: !include configs/recorder.yaml

#Setup Influx for use with Grafana
influxdb: !include configs/influxdb.yaml
