#Battery Alert Group
battery_alert:
  control: hidden
  entities:
    - input_number.battery_alert_threshold_min
    - input_number.battery_alert_threshold_max
    - automation.battery_notification
    - automation.battery_notification_clear
    - automation.battery_alert_html5
    - automation.battery_sensor_from_battery_level_attribute
    - automation.battery_sensor_from_battery_attribute
    - automation.battery_sensor_from_battery_numeric_attribute

