#Bedroom Group
bedroom_sensor_group:
  name: Bedroom Sensors
  control: hidden
  view: no
  entities:
    - sensor.bedroom_sensor_luminance
    - sensor.bedroom_sensor_relative_humidity
    - sensor.bedroom_sensor_temperature
    - binary_sensor.bedroom_multisensor_motion
    - binary_sensor.bedroom_multisensor_tamper 
    - sensor.bedroom_multisensor_batterylevel
