#Climate Groups
climate_sensor_group:
  name: HVAC
  control: hidden
  view: no
  entities:
    - climate.thermostat_heating_1
    - climate.thermostat_cooling_1

room_climate_group:
  name: Room Climate
  control: hidden
  view: no
  entities:
    - sensor.basement_sensor_temperature
    - sensor.basement_sensor_relative_humidity
    - sensor.main_floor_sensor_temperature
    - sensor.main_floor_sensor_relative_humidity
    - sensor.entryway_sensor_temperature
    - sensor.entryway_sensor_relative_humidity
    - sensor.garage_sensor_temperature
    - sensor.garage_sensor_relative_humidity
