#Door Group
door_sensors:
  name: Door Sensors
  control: hidden
  view: no
  entities:
    - binary_sensor.front_door_state
    - binary_sensor.kitchen_door_state
    - binary_sensor.game_room_main_door_state
    - binary_sensor.game_room_side_door_state
