#Garage Group
garage_sensor_group:
  name: Garage Sensors
  control: hidden
  view: no
  entities:
    - sensor.garage_sensor_luminance
    - sensor.garage_sensor_relative_humidity
    - sensor.garage_sensor_temperature
    - binary_sensor.garage_multisensor_motion
    - binary_sensor.garage_multisensor_tamper
    - sensor.garage_multisensor_batterylevel
