#Guest Room Group
guest_room_sensor_group:
  name: Guest Room Sensors
  control: hidden
  view: no
  entities:
    - sensor.guest_room_sensor_luminance
    - sensor.guest_room_sensor_relative_humidity
    - sensor.guest_room_sensor_temperature
    - binary_sensor.guest_room_multisensor_motion
    - binary_sensor.guest_room_multisensor_tamper 
    - sensor.guest_room_multisensor_batterylevel
