#Office Room Group
office_sensor_group:
  name: Office Sensors
  control: hidden
  view: no
  entities:
    - sensor.office_sensor_luminance
    - sensor.office_sensor_relative_humidity
    - sensor.office_sensor_temperature
    - binary_sensor.office_multisensor_motion
    - binary_sensor.office_multisensor_tamper 
    - sensor.office_multisensor_batterylevel
