#Saftey/Security Automation Group
saftey_autos_group:
  name: 'Saftey/Security'
  control: hidden
  view: no
  entities:
    - automation.co_detected
    - automation.fire_detected
    - automation.smoke_detector_testing_detected
    - automation.wx_alert_notification
    - automation.tts_and_notify_weather_alert

