#System Automation Group
system_autos_group:
  name: System
  control: hidden
  view: no
  entities:
    - automation.ssl_expiry_notification
    - automation.notify_on_failed_login
    - automation.update_google_assistant_on_start 

