#Testing Group
test_stuff:
  name: Testing Stuff
  control: hidden
  view: no
  entities:
    - sensor.dryer_voltage
    - sensor.dryer_previous_reading
    - sensor.dryer_power
    - sensor.dryer_energy
    - sensor.dryer_current
    - group.all_devices
