#Weather Groups
#
daily_forecast:
  name: Daily Forecast
  control: hidden
  view: no
  entities:
    - sensor.pws_weather_1d
    - sensor.pws_weather_1n
    - sensor.pws_weather_2d
    - sensor.pws_weather_2n

weather_overview:
  name: Weather overview
  control: hidden
  view: no
  entities:
    - sensor.pws_temp_high_1d_f
    - sensor.pws_temp_f
    - sensor.pws_temp_low_1d_f
    - sensor.pws_precip_1d
    - sensor.pws_precip_1d_in
    - sensor.pws_wind_mph
    - sensor.pws_wind_1d_mph
    - sensor.pws_alerts
