  user_room_location:
    name: !secret userTwoRoomLoc
    icon: mdi:account-heart
    options:
      - Basement
      - Garage
      - Main Floor
      - Entryway
      - Bedroom
      - Guest Room
      - Bathroom
      - Office
      - Away
      - Home
