###########################
# Hawk room location         
###########################
- platform: template
  sensors:
    basement_hawk_gh_rssi:
      value_template: >-
        {% if is_state("device_tracker.192_168_10_202_10_34_18_07_57_29", "home") %}
          {{state_attr('device_tracker.192_168_10_202_10_34_18_07_57_29', 'rssi')}}
        {% else %}
          -99
        {% endif %}

- platform: template
  sensors:
    garage_hawk_gh_rssi:
      value_template: >-
        {% if is_state("device_tracker.192_168_10_206_10_34_18_07_57_29", "home") %}
          {{state_attr('device_tracker.192_168_10_206_10_34_18_07_57_29', 'rssi')}}
        {% else %}
          -99
        {% endif %}
          
- platform: template
  sensors:
    bedroom_hawk_gh_rssi:
      value_template: >-
        {% if is_state("device_tracker.192_168_10_109_10_34_18_07_57_29", "home") %}
          {{state_attr('device_tracker.192_168_10_109_10_34_18_07_57_29', 'rssi')}}
        {% else %}
          -99
        {% endif %}



- platform: template
  sensors:
    office_hawk_gh_rssi:
      value_template: >-
        {% if is_state("device_tracker.192_168_10_56_10_34_18_07_57_29", "home") %}
          {{state_attr('device_tracker.192_168_10_56_10_34_18_07_57_29', 'rssi')}}
        {% else %}
          -99
        {% endif %}



- platform: template
  sensors:
    mainfloor_hawk_gh_rssi:
      value_template: >-
        {% if is_state("device_tracker.192_168_10_200_10_34_18_07_57_29", "home") %}
          {{state_attr('device_tracker.192_168_10_200_10_34_18_07_57_29', 'rssi')}}
        {% else %}
          -99
        {% endif %}

- platform: template
  sensors:
    entryway_hawk_gh_rssi:
      value_template: >-
        {% if is_state("device_tracker.192_168_10_118_10_34_18_07_57_29", "home") %}
          {{state_attr('device_tracker.192_168_10_118_10_34_18_07_57_29', 'rssi')}}
        {% else %}
          -99
        {% endif %}

- platform: template
  sensors:
    guestroom_hawk_gh_rssi:
      value_template: >-
        {% if is_state("device_tracker.192_168_10_154_10_34_18_07_57_29", "home") %}
          {{state_attr('device_tracker.192_168_10_154_10_34_18_07_57_29', 'rssi')}}
        {% else %}
          -99
        {% endif %}

- platform: template
  sensors:
    bathroom_hawk_gh_rssi:
      value_template: >-
        {% if is_state("device_tracker.192_168_10_201_10_34_18_07_57_29", "home") %}
          {{state_attr('device_tracker.192_168_10_201_10_34_18_07_57_29', 'rssi')}}
        {% else %}
          -99
        {% endif %}

- platform: template
  sensors:
    hawk_room_status:
      value_template: '{{ states.input_select.hawk_room_location.state }}'
      friendly_name: 'Hawk Location'
      icon_template: mdi:dog
