###########################
# Rambo room location         
###########################
- platform: template
  sensors:
    basement_rambo_gh_rssi:
      value_template: >-
        {% if is_state("device_tracker.192_168_10_202_10_34_18_07_82_65", "home") %}
          {{state_attr('device_tracker.192_168_10_202_10_34_18_07_82_65', 'rssi')}}
        {% else %}
          -99
        {% endif %}

- platform: template
  sensors:
    garage_rambo_gh_rssi:
      value_template: >-
        {% if is_state("device_tracker.192_168_10_206_10_34_18_07_82_65", "home") %}
          {{state_attr('device_tracker.192_168_10_206_10_34_18_07_82_65', 'rssi')}}
        {% else %}
          -99
        {% endif %}
          
- platform: template
  sensors:
    bedroom_rambo_gh_rssi:
      value_template: >-
        {% if is_state("device_tracker.192_168_10_109_10_34_18_07_82_65", "home") %}
          {{state_attr('device_tracker.192_168_10_109_10_34_18_07_82_65', 'rssi')}}
        {% else %}
          -99
        {% endif %}



- platform: template
  sensors:
    office_rambo_gh_rssi:
      value_template: >-
        {% if is_state("device_tracker.192_168_10_56_10_34_18_07_82_65", "home") %}
          {{state_attr('device_tracker.192_168_10_56_10_34_18_07_82_65', 'rssi')}}
        {% else %}
          -99
        {% endif %}



- platform: template
  sensors:
    mainfloor_rambo_gh_rssi:
      value_template: >-
        {% if is_state("device_tracker.192_168_10_200_10_34_18_07_82_65", "home") %}
          {{state_attr('device_tracker.192_168_10_200_10_34_18_07_82_65', 'rssi')}}
        {% else %}
          -99
        {% endif %}

- platform: template
  sensors:
    entryway_rambo_gh_rssi:
      value_template: >-
        {% if is_state("device_tracker.192_168_10_118_10_34_18_07_82_65", "home") %}
          {{state_attr('device_tracker.192_168_10_118_10_34_18_07_82_65', 'rssi')}}
        {% else %}
          -99
        {% endif %}

- platform: template
  sensors:
    guestroom_rambo_gh_rssi:
      value_template: >-
        {% if is_state("device_tracker.192_168_10_154_10_34_18_07_82_65", "home") %}
          {{state_attr('device_tracker.192_168_10_154_10_34_18_07_82_65', 'rssi')}}
        {% else %}
          -99
        {% endif %}

- platform: template
  sensors:
    bathroom_rambo_gh_rssi:
      value_template: >-
        {% if is_state("device_tracker.192_168_10_201_10_34_18_07_82_65", "home") %}
          {{state_attr('device_tracker.192_168_10_201_10_34_18_07_82_65', 'rssi')}}
        {% else %}
          -99
        {% endif %}

- platform: template
  sensors:
    rambo_room_status:
      value_template: '{{ states.input_select.rambo_room_location.state }}'
      friendly_name: 'Rambo Location'
      icon_template: mdi:dog
