- alias: 'Admin arrived home'
  condition:
   - condition: state
     entity_id: device_tracker.galaxy_note10
     state: 'not_home'
  trigger:
    platform: state
    entity_id: device_tracker.d463c65d0c74
    from: 'not_home'
    to: 'home'
  action:
    service: notify.notify
    data_template:
      message: >
        {{ states.device_tracker.d463c65d0c74.attributes.friendly_name }} arrived home
      target: !secret userPhone 
- alias: 'User arrived home'
  condition:
    - condition: state
      entity_id: device_tracker.d463c65d0c74
      state: 'not_home'
  trigger:
    platform: state
    entity_id: device_tracker.galaxy_note10
    from: 'not_home'
    to: 'home'
  action:
    service: notify.notify
    data_template:
      message: >
        {{ states.device_tracker.galaxy_note10.attributes.friendly_name }} arrived home
      target: !secret adminPhone

