- alias: 'Admin arrived home'
  condition:
   - condition: state
     entity_id: person.jennifer
     state: 'not_home'
  trigger:
    platform: state
    entity_id: person.logan
    from: 'not_home'
    to: 'home'
  action:
    service: notify.user
    data_template:
      message: >
        {{ states.person.logan.attributes.friendly_name }} arrived home
- alias: 'User arrived home'
#  condition:
#    - condition: state
#      entity_id: person.logan
#      state: 'not_home'
  trigger:
    platform: state
    entity_id: person.jennifer
    from: 'not_home'
    to: 'home'
  action:
    service: notify.admin
    data_template:
      message: >
        {{ states.person.jennifer.attributes.friendly_name }} arrived home

