- alias: 'Game Room Door Opened At Night'
  trigger:
    platform: state
    entity_id: binary_sensor.game_room_main_door_access_control_door_window_open, binary_sensor.game_room_side_door_access_control_door_window_open
    to: 'on'
  condition:
    - condition: sun
      after: sunset
      after_offset: "-0:20:00"
  action:
    - service: homeassistant.turn_on
      entity_id: switch.patio_light_switch, switch.patio_side_light_switch, switch.garage_rear_light_switch

- alias: 'Game Room Door Closed At Night'
  trigger:
    platform: state
    entity_id: binary_sensor.game_room_main_door_access_control_door_window_open, binary_sensor.game_room_side_door_access_control_door_window_open
    to: 'off'
    for:
      minutes: 3
  condition:
    - condition: sun
      after: sunset
      after_offset: "-0:20:00"
  action:
    - service: homeassistant.turn_off
      entity_id: switch.patio_light_switch, switch.patio_side_light_switch, switch.garage_rear_light_switch

- alias: 'Game Room Door Open At Night'
  trigger:
    platform: sun
    event: sunset
    offset: '-00:20:00'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.game_room_main_door_access_control_door_window_open
        state: 'on'
      - condition: state
        entity_id: binary_sensor.game_room_side_door_access_control_door_window_open
        state: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.patio_light_switch, switch.patio_side_light_switch, switch.garage_rear_light_switch
