#Turn on MQTT Lights once a day at 10am to keep them connected to Wifi
- alias: MQTT Lights KeepAlive ON
  trigger:
    - platform: time
      at: '10:00:00'
  action:
    - service: homeassistant.turn_on
      entity_id: light.bedroom_lamps,light.guest_bedroom_lamp,light.office_lamp

#Turn off MQTT Lights once a day after lights turn on at 10am
- alias: MQTT Lights KeepAlive OFF
  trigger:
    - platform: time
      at: '10:05:00'
  action:
    service: homeassistant.turn_off
    entity_id: light.bedroom_lamps,light.guest_bedroom_lamp,light.office_lamp
