#Activate Night Mode when TV turns off after 8PM
- alias: Night Mode
  trigger:
    platform: state
    entity_id: device_tracker.samsung_tv
    from: 'home'
    to: 'not_home'
#    entity_id: media_player.basement_tv
#    from: 'on'
#    to: 'off'
  condition:
    - condition: time
      after: '20:00'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.bedroom_lamps
        brightness: 255
        rgb_color: [255,0,0]
        white_value: 20
    - service: light.turn_on
      data_template:
        entity_id: light.bedroom_lamps
        brightness: 10
        rgb_color: [255,0,0]
        white_value: 0
        transition: 900
    - delay: '00:15:00'
    - service: light.turn_off
      data_template:
        entity_id: light.bedroom_lamps
