- alias: 'Plants Need Water'
  trigger:
    platform: state
    entity_id: sensor.marilyn_status
    from: 'Optimal'
  action:
    - service: notify.user
      data_template:
        title: Check {{ trigger.to_state.attributes.friendly_name }}
        message: >
          Soil Status: {{ trigger.to_state.state }}

          {%set s = trigger.to_state.entity_id | replace("status","moisture") %}
          Moisture Level: {{ states(s) }}%
