#Bedroom Wakeup Sunrise Simulation
  wakeup_bedroom:
    sequence:
      - service: light.turn_on
        data_template:
          entity_id: light.bedroom_lamps
          brightness: 1
          rgb_color: [128,0,0]
          white_value: 0
      - service: light.turn_on
        data_template:
          entity_id: light.bedroom_lamps
          brightness: 41
          rgb_color: [128,0,0]
          white_value: 0
          transition: '{{ (( states.input_number.wakeup_duration.state | float * 60 / 7 - 1 ) | round ) | int }}'
      - delay: '00:00:{{ (( states.input_number.wakeup_duration.state | float * 60 / 7 ) | round ) | int }}'
      - service: light.turn_on
        data_template:
          entity_id: light.bedroom_lamps
          brightness: 81
          rgb_color: [192,64,0]
          white_value: 0
          transition: '{{ (( states.input_number.wakeup_duration.state | float * 60 / 7 - 1 ) | round ) | int }}'
      - delay: '00:00:{{ (( states.input_number.wakeup_duration.state | float * 60 / 7 ) | round ) | int }}'
      - service: light.turn_on
        data_template:
          entity_id: light.bedroom_lamps
          brightness: 121
          rgb_color: [224,128,32]
          white_value: 0
          transition: '{{ (( states.input_number.wakeup_duration.state | float * 60 / 7 - 1 ) | round ) | int }}'
      - delay: '00:00:{{ (( states.input_number.wakeup_duration.state | float * 60 / 7 ) | round ) | int }}'
      - service: light.turn_on
        data_template:
          entity_id: light.bedroom_lamps
          brightness: 161
          rgb_color: [255,176,96]
          white_value: 0
          transition: '{{ (( states.input_number.wakeup_duration.state | float * 60 / 7 - 1 ) | round ) | int }}'
      - delay: '00:00:{{ (( states.input_number.wakeup_duration.state | float * 60 / 7 ) | round ) | int }}'
      - service: light.turn_on
        data_template:
          entity_id: light.bedroom_lamps
          brightness: 201
          rgb_color: [255,224,160]
          white_value: 0
          transition: '{{ (( states.input_number.wakeup_duration.state | float * 60 / 7 - 1 ) | round ) | int }}'
      - delay: '00:00:{{ (( states.input_number.wakeup_duration.state | float * 60 / 7 ) | round ) | int }}'
      - service: light.turn_on
        data_template:
          entity_id: light.bedroom_lamps
          brightness: 221
          rgb_color: [255,255,224]
          white_value: 0
          transition: '{{ (( states.input_number.wakeup_duration.state | float * 60 / 7 - 1 ) | round ) | int }}'
      - delay: '00:00:{{ (( states.input_number.wakeup_duration.state | float * 60 / 7 ) | round ) | int }}'
      - service: light.turn_on
        data_template:
          entity_id: light.bedroom_lamps
          brightness: 255
          rgb_color: [240,255,255]
          white_value: 0
          transition: '{{ (( states.input_number.wakeup_duration.state | float * 60 / 7 - 1 ) | round ) | int }}'
#      - delay: '00:00:{{ (( states.input_number.wakeup_duration.state | float * 60 / 7 ) | round ) | int }}'
#      - delay: '00:{{ states.input_number.wakeup_delay.state | int }}:{{ ((states.input_number.wakeup_duration.state | float * 60 / 7 ) | round ) | int }}'
      - delay: '00:{{ states.input_number.wakeup_delay.state | int }}'
      - service: switch.turn_on
        entity_id: switch.bedroom_light_switch

