#Change to Fire TV Media settings for basement TV
  firetv:
    sequence:
     - service: media_player.turn_on
       entity_id: media_player.basement_tv
     - service: media_player.turn_on
       entity_id: media_player.txrz800
     - service: media_player.select_source
       data:
         entity_id: media_player.txrz800
         source: FireTV
     - service: media_player.volume_set
       data:
         entity_id: media_player.txrz800
         volume_level: .625
       
