  media_player:
   - host: !secret gh_basement
  media_player:
   - host: !secret gh_garage
  media_player:
   - host: !secret gh_mainfloor
  media_player:
   - host: !secret gh_entryway
  media_player:
   - host: !secret gh_bedroom
  media_player:
   - host: !secret gh_guestroom
  media_player:
   - host: !secret gh_bathroom
  media_player:
   - host: !secret gh_office
  media_player:
   - host: !secret cc_basement
