 #OUTLETS
  switch.outlet_1_switch:
    friendly_name: Main Level Outlet 1
  switch.outlet_2_switch:
    friendly_name: Main Level Outlet 2
 #ALARM
  sensor.wakeup_alarm_time:
    icon: mdi:timer
  sensor.wakeup_fadein_duration:
    icon: mdi:timer
  sensor.wakeup_start_time_lights:
    icon: mdi:timer
 #SMOKE Detectors
  sensor.basement_smoke_co2:
    friendly_name: "Basement Smoke Detector"          
  sensor.upstairs_smoke_co2:
    friendly_name: "Upstairs Smoke Detector"          
  sensor.entryway_smoke_co2:
    friendly_name: "Entryway Smoke Detector"
 #LIGHTS
  light.bedroom_lamps:
    icon: mdi:lamp
  light.guest_bedroom_lamp:
    friendly_name: "Guest Room Lamp"
    icon: mdi:lamp
  light.office_lamp:
    icon: mdi:lamp
  light.basement_light_level:
    friendly_name: "Basement Light"
  light.kitchen_light_level:
    friendly_name: "Kitchen Light"
  light.office_light_level:
    friendly_name: "Office Light"
 #WASHING MACHINE
  binary_sensor.washing_machine:
    icon: mdi:washing-machine
  binary_sensor.dryer_running:
    icon: mdi:tumble-dryer
  binary_sensor.dryer_cooldown:
    icon: mdi:tumble-dryer
#UPS
  sensor.nut_ups_status:
    friendly_name: "UPS Status"
  sensor.nut_ups_nominal_real_power:
    friendly_name: "Input Power"
  sensor.nut_ups_input_voltage:
    friendly_name: "Input Voltage"
  sensor.nut_ups_battery_charge:
    friendly_name: "UPS Battery"
    battery_sensor_creation_disabled: true
  sensor.nut_ups_load:
    friendly_name: "UPS Load"
  sensor.nut_ups_battery_runtime:
    friendly_name: "Time Left"
    unit_of_measurement: 'seconds'
