project_id: !secret ga_project_id
client_id: !secret ga_client_id
access_token: !secret ga_access_token
agent_user_id: !secret ga_agent_user_id
api_key: !secret ga_api_key
exposed_domains:
  - switch
  - light
  - fan
  - scene

