project_id: !secret ga_project_id
api_key: !secret ga_api_key
exposed_domains:
  - switch
  - light
  - fan
  - scene
entity_config:
  switch.ups_outlet_switch:
    expose: false
  switch.bedroom_light_switch:
    name: Bedroom Fan Light
