  #ALARM CLOCK
  wakeup_hour:
    name: Hour
    icon: mdi:clock-in
    initial: 6
    min: 0
    max: 23
    step: 1
  
  wakeup_minutes:
    name: Minutes
    icon: mdi:clock-in
    initial: 00
    min: 0
    max: 55
    step: 5
  
  wakeup_duration:
    name: Fade Time
    icon: mdi:clock-in
    initial: 30
    min: 5
    max: 60
    step: 5

  wakeup_delay:
    name: Overhead Delay
    icon: mdi:clock-in
    initial: 10
    min: 0
    max: 60
    step: 5

  #MAIN FLOOR CAMERA
  main_floor_pan:
    name: Main Floor Pan Position
    min: 0
    max: 100
    step: 1

  main_floor_tilt:
    name: Main Floor Tilt Position
    min: 0
    max: 100
    step: 1
