#####################
#LOGGING.yaml       #
#####################

#enabling logging for troubleshooting
  default: error
  logs:
    homeassistant.components.http.ban: warning
    #homeassistant.components.media_player.samsungtv: debug
    #homeassistant.components.device_tracker: debug
    #homeassistant.components.mqtt: debug
