##########################################
#MEDIA YAML CONFIGURATION FILE media.yaml
##########################################

# Add Onkyo Reciever
  - platform: onkyo
    host: !secret onkyo_host
    name: "TX-RZ800"
    sources:
      strm-box: "ShieldTV"
      dvd: "PS3"
