##########################################
#MEDIA YAML CONFIGURATION FILE media.yaml
##########################################


# Add Onkyo Reciever
  - platform: onkyo
    host: !secret onkyo_host
    name: "TX-RZ800"
    sources:
      strm-box: "FireTV"
      video2: "Basement Chromecast"
      dvd: "PS3"
#Add Basement TV
  - platform: samsungtv
    name: "Basement TV"
    host: !secret samsung_host
    port: !secret samsung_port
    mac: !secret samsung_mac
#Add Google Homes
  - platform: cast
    host: !secret gh_basement
  - platform: cast
    host: !secret gh_garage
  - platform: cast
    host: !secret gh_mainfloor
  - platform: cast
    host: !secret gh_entryway
  - platform: cast
    host: !secret gh_bedroom
  - platform: cast
    host: !secret gh_guestroom
  - platform: cast
    host: !secret gh_bathroom
  - platform: cast
    host: !secret gh_office
  - platform: cast
    host: !secret cc_basement
#  - platform: cast
#    host: !secret cc_mainfloor
