  - name: notify
    platform: html5
    vapid_pub_key: !secret vapPubKey
    vapid_prv_key: !secret vapPrvKey
    vapid_email: !secret vapEmail

  - platform: group
    name: both_phones
    services:
      - service: mobile_app_pixel_4a_5g
      - service: mobile_app_sm_n986u1

  - platform: group
    name: admin
    services:
      - service: mobile_app_pixel_4a_5g

  - platform: group
    name: user
    services:
      - service: mobile_app_sm_n986u1
