  - name: notify
    platform: html5
    vapid_pub_key: !secret vapPubKey
    vapid_prv_key: !secret vapPrvKey
    vapid_email: !secret vapEmail

  - platform: group
    name: admin_phone
    services:
      - service: notify
        data:
          target: !secret adminPhone

  - platform: group
    name: user_phone
    services:
      - service: notify
        data:
          target: !secret userPhone

  - platform: group
    name: both_phones
    services:
      - service: notify
        data:
          target: !secret adminPhone
      - service: notify
        data:
          target: !secret userPhone
