#Automation View
#
automations:
  name: automations
  view: yes
  entities:
    - group.convenience_autos_group
    - group.presence_autos_group
    - group.saftey_autos_group
    - group.maitenance_autos_group
    - group.system_autos_group
    - group.battery_alert
    #- group.all_automations
