#Basement View
#
basement:
  name: Basement
  control: hidden
  view: yes
  entities:
    - group.basment_sensor_group
    - media_player.basement_speaker
    - media_player.basement_tv
    - media_player.basement
    - media_player.txrz800
