#Climate View
#
climate:
  name: Climate
  control: hidden
  view: yes
  entities:
    - group.daily_forecast
    - group.climate_sensor_group
    - group.weather_overview
    - group.room_climate_group
