#Default View
#
default_view:
  view: yes
  icon: mdi:home 
  entities:
    - group.door_sensors
    - group.motion_sensors
    - group.smoke_detectors
    - group.laundry
    - group.all_devices
    - group.all_switches
    - group.all_fans
    - group.all_lights
    - group.all_covers
