###########################
# fail2ban sensors
###########################
- platform: fail2ban
  jails:
    - hass-iptables
    - ssh   
#  file_path: /etc/fail2ban/log/fail2ban.log
  scan_interval: 60
