###########################
# fail2ban sensors
###########################
- platform: fail2ban
  jails:
    - sshd
    - traefik-auth
    - traefik-badbots
    - traefik-botsearch
  file_path: /etc/fail2ban/log/fail2ban.log
  scan_interval: 60
