###########################
# Plant Sensors                 
###########################

#Marilyn
- platform: rest
  resource: !secret plant_resource
  method: GET
  authentication: basic
  headers:
    Authorization: !secret plant_auth
  verify_ssl: false
  name: Plant Name
  value_template: "{{ value_json.name }}"
  scan_interval: 3600
- platform: rest
  resource: !secret plant_resource
  method: GET
  authentication: basic
  headers:
    Authorization: !secret plant_auth
  verify_ssl: false
  name: Marilyn Status
  scan_interval: 3600
  value_template: >
         {% if value_json.status | int == 0 %}
           Too Dry
         {% elif value_json.status | int == 1 %}
           Dry
         {% elif value_json.status | int == 2 %}
           Optimal
         {% elif value_json.status | int == 3 %}
           Wet
         {% elif value_json.status | int == 4 %}
           Too Wet
         {% else %}
           value_json.status
         {% endif %}
  icon_template: >
         {% if value_json.status | int == 0 %}
           mdi:water
         {% elif value_json.status | int == 1 %}
           mdi:water
         {% elif value_json.status | int == 2 %}
           mdi:water-off
         {% elif value_json.status | int == 3 %}
           mdi:water-off
         {% elif value_json.status | int == 4 %}
           mdi:water-off
         {% else %}
           mdi:water-off
         {% endif %}
- platform: rest
  resource: !secret plant_resource
  method: GET
  authentication: basic
  headers:
    Authorization: !secret plant_auth
  verify_ssl: false
  scan_interval: 3600
  name: Marilyn Moisture
  sensor_class: moisture
  unit_of_measurement: '%'
  value_template: '{{ ((value_json.last_measurements[0]["moisture"]) * 100) | round(0) }}'
