###########################
# UPS Friently Time Left         
###########################
- platform: template
  sensors:  
    deathstarups_runtime_friendly:
      friendly_name: 'Time Remaining'
      value_template: >- 
        {% set time = (states.sensor.deathstarups_battery_runtime.state | int) | int %}
        {% set minutes = ((time % 3600) / 60) | int %}
        {% set hours = ((time % 86400) / 3600) | int %}
        {% set days = (time / 86400) | int %}
        
        {%- if time < 60 -%}
          Less than a minute
        {%- else -%}
          {%- if days > 0 -%}
            {{ days }}d
          {%- endif -%}
          {%- if hours > 0 -%}
            {%- if days > 0 -%}
              {{ ' ' }}
            {%- endif -%}
            {{ hours }}h
          {%- endif -%}
          {%- if minutes > 0 -%}
            {%- if days > 0 or hours > 0 -%}
              {{ ' ' }}
            {%- endif -%}
            {{ minutes }}m
          {%- endif -%}
        {%- endif -%}
    nut_ups_runtime_minutes:
      friendly_name: 'Minutes Remaining'
      unit_of_measurement: 'm'
      value_template: >- 
        {% set time = (states.sensor.deathstarups_battery_runtime.state | int) | int %}
        {% set minutes = (time / 60) | int %}
          {{ minutes }}
