###########################
# Weather
###########################
- platform: wunderground
  api_key: !secret wu_api_key
  monitored_conditions:
    - weather_1d
    - weather_1n
    - weather_2d
    - weather_2n
    - temp_high_1d_f
    - temp_f
    - temp_low_1d_f
    - precip_1d
    - precip_1d_in
    - wind_mph
    - wind_1d_mph
    - alerts
