  hawk_basement_presence:
    name: Hawk Basement Presence
    initial: false

  hawk_garage_presence:
    name: Hawk Garage Presence
    initial: false

  hawk_bedroom_presence:
    name: Hawk Bedroom Presence
    initial: false

  hawk_office_presence:
    name: Hawk Office Presence
    initial: false

  hawk_mainfloor_presence:
    name: Hawk Main Floor Presence
    initial: false

  hawk_entryway_presence:
    name: Hawk Entryway Presence
    initial: false

  hawk_guestroom_presence:
    name: Hawk Guest Room Presence
    initial: false

  hawk_bathroom_presence:
    name: Hawk Bathroom Presence
    initial: false
