  user_basement_presence:
    name: User Basement Presence
    initial: false

  user_garage_presence:
    name: User Garage Presence
    initial: false

  user_bedroom_presence:
    name: User Bedroom Presence
    initial: false

  user_office_presence:
    name: User Office Presence
    initial: false

  user_mainfloor_presence:
    name: User Main Floor Presence
    initial: false

  user_entryway_presence:
    name: User Entryway Presence
    initial: false

  user_guestroom_presence:
    name: User Guest Room Presence
    initial: false

  user_bathroom_presence:
    name: User Bathroom Presence
    initial: false
