###########################
# Door Sensors                 
###########################
- platform: template
  sensors:  
    front_door_tamper:
      friendly_name: 'Front Door Tampering'
      device_class: vibration
      value_template: "{{ is_state('sensor.front_door_burglar','3') }}"
    front_door_state:
      friendly_name: 'Front Door'
      device_class: door
      value_template: "{{ (not is_state('sensor.front_door_access_control','23')) }}"

#    kitchen_door_tamper:
#      friendly_name: 'Kitchen Door Tampering'
#      device_class: vibration
#      value_template: "{{ is_state('sensor.kitchen_door_burglar','3') }}"
#    kitchen_door_state:
#      friendly_name: 'Kitchen Door'
#      device_class: door
#      value_template: "{{ (not is_state('sensor.kitchen_door_access_control','23')) }}"
#

    game_room_main_door_tamper:
      friendly_name: 'Game Room Main Door Tampering'
      device_class: vibration
      value_template: "{{ is_state('sensor.game_room_main_door_burglar','3') }}"
    game_room_main_door_state:
      friendly_name: 'Game Room Main Door'
      device_class: door
      value_template: "{{ (not is_state('sensor.game_room_main_door_access_control','23')) }}"

    game_room_side_door_tamper:
      friendly_name: 'Game Room Side Door Tampering'
      device_class: vibration
      value_template: "{{ is_state('sensor.game_room_side_door_burglar','3') }}"
    game_room_side_door_state:
      friendly_name: 'Game Room Side Door'
      device_class: door
      value_template: "{{ (not is_state('sensor.game_room_side_door_access_control','23')) }}"
